import NavBar from "@/components/NavBar";
import ReadtQueryClientProvider from "@/components/ReadtQueryClientProvider";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReadtQueryClientProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <NavBar />
          {children}
        </body>
      </html>
    </ReadtQueryClientProvider>
  );
}
